
model_list:
  # Embedding model
  - model_name: intfloat/multilingual-e5-large
    litellm_params:
      model: watsonx/intfloat/multilingual-e5-large
      embedding_dimensions: "os.environ/EMBEDDING_DIM"
      api_key: "os.environ/WATSONX_API_KEY"
      project_id: "os.environ/WATSONX_PROJECT_ID"
      url: "os.environ/WATSONX_URL"
      input_cost_per_token: 0.0000001
      output_cost_per_token: 0.0000001
    model_info:
      mode: embedding

  # LLM model for text/completions
  - model_name: openai/gpt-oss-120b
    litellm_params:
      model: watsonx/openai/gpt-oss-120b
      api_key: "os.environ/WATSONX_API_KEY"
      project_id: "os.environ/WATSONX_PROJECT_ID"
      url: "os.environ/WATSONX_URL"

general_settings:
  master_key: sk-1234
  disable_fallbacks: true
  enforce_model_usage: true
  log_level: debug
  store_model_in_db: true
  store_prompts_in_spend_logs: true

litellm_settings:
  drop_params: true
